import{a as L,S,i as n}from"./assets/vendor-CucEYOFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const v="56486035-b8f00db38e9e416252e8b1b7d",w="https://pixabay.com/api/";async function u(e,o=1){const s={key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await L.get(w,{params:s})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader-container"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function h(e){const o=e.map(({webformatURL:s,largeImageURL:i,tags:t,likes:r,views:a,comments:y,downloads:b})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${s}" alt="${t}" />
        </a>
        <div class="info-wrapper">
          <p class="info-item"><b>Likes</b><br>${r}</p>
          <p class="info-item"><b>Views</b><br>${a}</p>
          <p class="info-item"><b>Comments</b><br>${y}</p>
          <p class="info-item"><b>Downloads</b><br>${b}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",o),P.refresh()}function q(){m.innerHTML=""}function E(){f.classList.remove("is-hidden")}function p(){f.classList.add("is-hidden")}const R=document.querySelector(".form"),c=document.querySelector(".load-more-btn");let d="",l=1;const $=15;R.addEventListener("submit",x);c.addEventListener("click",M);async function x(e){if(e.preventDefault(),d=e.currentTarget.elements["search-text"].value.trim(),d===""){n.warning({message:"Please enter a valid search term!",position:"topRight"});return}l=1,q(),c.classList.add("is-hidden"),E();try{const s=await u(d,l);if(s.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(s.hits),g(s.totalHits)}catch(s){n.error({title:"Error",message:s.message,position:"topRight"})}finally{p()}}async function M(){l+=1,c.classList.add("is-hidden");try{const e=await u(d,l);h(e.hits),O(),g(e.totalHits)}catch(e){n.error({title:"Error",message:e.message,position:"topRight"})}finally{p()}}function g(e){const o=Math.ceil(e/$);l>=o?(c.classList.add("is-hidden"),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):c.classList.remove("is-hidden")}function O(){const e=document.querySelector(".gallery-item");if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
