import{a as w,S as v,i as n}from"./assets/vendor-CucEYOFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const P="56486035-b8f00db38e9e416252e8b1b7d",q="https://pixabay.com/api/";async function u(e,o=1){const s={key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await w.get(q,{params:s})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader-container"),h=document.querySelector(".load-more-btn"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(e){const o=e.map(({webformatURL:s,largeImageURL:a,tags:t,likes:r,views:i,comments:L,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${s}" alt="${t}" />
        </a>
        <div class="info-wrapper">
          <p class="info-item"><b>Likes</b><br>${r}</p>
          <p class="info-item"><b>Views</b><br>${i}</p>
          <p class="info-item"><b>Comments</b><br>${L}</p>
          <p class="info-item"><b>Downloads</b><br>${S}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",o),M.refresh()}function B(){m.innerHTML=""}function g(){f.classList.remove("is-hidden")}function y(){f.classList.add("is-hidden")}function $(){h.classList.remove("is-hidden")}function d(){h.classList.add("is-hidden")}const E=document.querySelector(".form"),R=document.querySelector(".load-more-btn");let l="",c=1;const x=15;E.addEventListener("submit",O);R.addEventListener("click",H);async function O(e){if(e.preventDefault(),l=e.currentTarget.elements["search-text"].value.trim(),l===""){n.warning({message:"Please enter a valid search term!",position:"topRight"});return}c=1,B(),d(),g();try{const s=await u(l,c);if(s.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(s.hits),b(s.totalHits)}catch(s){n.error({title:"Error",message:s.message,position:"topRight"})}finally{y()}}async function H(){c+=1,d(),g();try{const e=await u(l,c);p(e.hits),A(),b(e.totalHits)}catch(e){n.error({title:"Error",message:e.message,position:"topRight"})}finally{y()}}function b(e){const o=Math.ceil(e/x);c>=o?(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):$()}function A(){const e=document.querySelector(".gallery-item");if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
